<#
.SYNOPSIS
    Export behavioural data from Supabase to timestamped JSON (PowerShell 5.1).
.DESCRIPTION
    Dumps signal, venue_dish, trip_party, party_member tables to backups/.
    These contain Laos behavioural data that cannot be regenerated by rebuild.
    backups/ is gitignored.
.NOTES
    Requires: .env with TB_SUPABASE_URL and TB_SUPABASE_KEY (service_role).
#>
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

Write-Host "`n========== Travel Buddy: Export Signals ==========" -ForegroundColor Cyan

# ─── Load .env ───────────────────────────────────────────────────────────────
$envPath = Join-Path $PSScriptRoot '..\.env'
if (-not (Test-Path $envPath)) {
    Write-Host "FATAL: .env not found. Run start-backend.ps1 first." -ForegroundColor Red
    exit 1
}
$envContent = Get-Content $envPath
$supaUrl = $null
$supaKey = $null
foreach ($line in $envContent) {
    if ($line -match '^TB_SUPABASE_URL=(.+)) { $supaUrl = $Matches[1].Trim() }
    if ($line -match '^TB_SUPABASE_KEY=(.+)) { $supaKey = $Matches[1].Trim() }
}
if (-not $supaUrl -or -not $supaKey) {
    Write-Host "FATAL: TB_SUPABASE_URL or TB_SUPABASE_KEY missing from .env" -ForegroundColor Red
    exit 1
}

# ─── Create backups dir ──────────────────────────────────────────────────────
$timestamp = Get-Date -Format 'yyyy-MM-dd_HHmmss'
$backupDir = Join-Path $PSScriptRoot "..\backups\$timestamp"
New-Item -ItemType Directory -Path $backupDir -Force | Out-Null
Write-Host "  Backup dir: backups\$timestamp\" -ForegroundColor Green

# ─── Export tables ───────────────────────────────────────────────────────────
$tables = @('signal', 'venue_dish', 'trip_party', 'party_member')

foreach ($table in $tables) {
    $url = "$supaUrl/rest/v1/$table?select=*"
    $outFile = Join-Path $backupDir "$table.json"
    Write-Host "  Exporting $table..." -NoNewline
    try {
        $data = curl.exe -s $url `
            -H "apikey: $supaKey" `
            -H "Authorization: Bearer $supaKey" `
            -H 'Accept: application/json'
        $data | Out-File -Encoding utf8 $outFile
        $count = ($data | ConvertFrom-Json).Count
        Write-Host " $count rows" -ForegroundColor Green
    } catch {
        Write-Host " ERROR: $_" -ForegroundColor Red
    }
}

Write-Host "`n  Done. Files in: backups\$timestamp\" -ForegroundColor Cyan
Write-Host "  (gitignored — commit manually if you want them in source control)`n" -ForegroundColor DarkGray
